#!/usr/bin/env python
# Generate ds-relay-local.yaml + ds-relay-hybrid.yaml by patching the
# PROVEN ds-team-flash.yaml (22/22 smoke + 5/5 method). Member prompts are
# byte-identical by construction; only the leader prompt gains a RELAY
# section and the config blocks change. Every anchor is asserted so baseline
# drift fails loudly instead of silently producing a wrong profile.
import io, os, sys

HERE = os.path.dirname(os.path.abspath(__file__))
SRC = os.path.join(HERE, "ds-team-flash.yaml")
DST_LOCAL = os.path.join(HERE, "ds-relay-local.yaml")
DST_HYBRID = os.path.join(HERE, "ds-relay-hybrid.yaml")

text = io.open(SRC, encoding="utf-8", newline="").read()

def patch(t, old, new, label):
    if old not in t:
        print("ANCHOR MISSING: %s" % label); sys.exit(1)
    if t.count(old) != 1:
        print("ANCHOR NOT UNIQUE (%d): %s" % (t.count(old), label)); sys.exit(1)
    return t.replace(old, new)

# ---------------- 1. header (name + description, up to sandbox:) ----------
i = text.index("sandbox:")
HEADER_LOCAL = """name: ds-relay-local
description: |
  RELAY MODE, LOCAL-ONLY (M1, 2026-07-10): the autonomous-generation
  profile from 24h-architecture-v1.md section 1.5. Pure DeepSeek-V4-Flash
  on the DGX Sparks (TP=2), $0. One run of this profile = ONE GENERATION
  in the relay: boot from the board, land slices, commit with Slice:
  trailers, exit DONE | HANDOFF | BLOCKED. The supervisor respawns the
  next generation; the boot reconciler verifies the board first.

  Member prompt set is byte-identical to ds-team-flash.yaml (proven
  22/22 smoke + 5/5 method) - generated by gen_relay_profiles.py; do NOT
  edit prompts here, fix the baseline and regenerate. The leader prompt
  ADDS the relay/baton operating rules (boot, slice loop, stagger,
  heartbeat, park, exit contract).

  Config deltas vs ds-team-flash (all from the measured capacity study
  docs/infra/deepseek-v4-flash-dgx.md):
    - relay block ARMED: 65536 window, handoff at 65% (~42.6K real
      tokens; R1 nudge fires BEFORE the 50K leader compaction net)
    - token budgets: leader 50K, implementer 30K, researcher/reviewer
      20K (sum ~120K = one team inside the distinct-KV pool)
    - bind deepseek-v4-flash EXPLICITLY (aeon-mtp is an alias that has
      silently swapped models before - never bind it)
    - thinking stays OFF everywhere: same tok/s, ~2.5x tokens = slower
      generations (capacity study). NOTE 2026-07-10: the DSpark build
      DOES honor chat_template_kwargs.enable_thinking (bench-thread wire
      probe, ~2.15x tokens) - the old "Qwen3-only kwarg" claim is wrong.
      A relay thinking A/B is one profile-knob flip if the bench A/B
      shows solve-rate gains.

  FIRST 24h run uses THIS profile with pre-authored plan.md files
  (measures Flash alone; a hybrid first run never can).

"""
HEADER_HYBRID = """name: ds-relay-hybrid
description: |
  RELAY MODE, HYBRID (M1, 2026-07-10): same relay spine as
  ds-relay-local (generated from the same baseline - member prompts
  byte-identical) with ONE difference in-run: the reviewer member is
  DeepSeek-V4-PRO via OpenRouter (the proven ds-team-lead-pro pattern -
  Pro judgment on diffs, Flash everywhere else). The Pro plan-pass and
  Pro whole-feature reviewer BOOKENDS are supervisor-side calls, not
  part of this profile; the T7 escalation ladder lives in
  ds-team-flash-escalate (M6), not here.

  Requires: DEEPSEEK_API_KEY = OpenRouter token (reviewer only).
  This is v1.1 - adopt where the local run's parked/failed items show
  Pro would have paid for itself. Config deltas vs the baseline are the
  same as ds-relay-local (relay block armed, 50K/30K/20K budgets,
  deepseek-v4-flash bound explicitly, thinking off).

"""
local = HEADER_LOCAL + text[i:]
# hybrid built from local at the end.

# ---------------- 2. root compaction 100k -> 50k + relay block ------------
OLD_COMPACT = """compaction:
  threshold_tokens: 100000
  keep_last_messages: 8
"""
NEW_COMPACT = """# Leader budget from the capacity study: 50K. The relay handoff nudge
# (65% of 65536 = ~42.6K REAL tokens) fires BEFORE this estimator-based
# net, so a healthy generation hands off instead of compacting; compaction
# only catches a leader that overran the nudge mid-dispatch.
compaction:
  threshold_tokens: 50000
  keep_last_messages: 8

# R1 armed: real per-response Usage.InputTokenCount vs the served window;
# crossing 65% injects the wrap-up/HANDOFF nudge (re-nudges +5).
#
# ⚠ 65536 IS STALE-BUT-SAFE, NOT MEASURED-CURRENT. gpu-1 re-measured at
# max_model_len 131072 on 2026-08-28. Left unchanged ON PURPOSE: this is a
# live VALUE that reshapes every generated relay profile, so raising it is
# a behaviour change that wants its own run, not a comment sweep. Handing
# off at ~42.6K on a 131072 server is EARLY, never unsafe.
relay:
  context_window: 65536
  handoff_threshold_pct: 65
"""
local = patch(local, OLD_COMPACT, NEW_COMPACT, "root compaction block")

# ---------------- 3. leader prompt: append relay rules --------------------
# Anchor = end of the leader FINAL MESSAGE CONTRACT + the max_iterations
# comment that follows the prompt block.
OLD_LEADER_END = """        Use `low` whenever tests didn't run, a member reported
        uncertainty, or you couldn't fully verify the change.
    # 200, not 25:"""
RELAY_RULES = """        Use `low` whenever tests didn't run, a member reported
        uncertainty, or you couldn't fully verify the change.

      ================ RELAY / BATON OPERATING RULES ================
      You are ONE GENERATION in a relay. A supervisor booted you after
      a script verified the board; a successor generation continues
      after you. Your job is to land verified slices and exit clean -
      NOT to finish everything.

      BOOT (your first tool calls, in this order): read these files at
      the board path named in your task:
        1. handoff-current.md  - where the last generation stopped
        2. plan.md             - feature spec + slice checklist + THE
                                 GATE COMMAND (authoritative for this
                                 feature; it overrides the generic
                                 dotnet-test rule above)
        3. state.json          - per-slice status. The boot reconciler
                                 already verified it against git: trust
                                 it, do NOT re-derive history from
                                 git log, do NOT read old handoffs or
                                 journal files.

      SLICE LOOP: take the first slice with status "todo" whose
      dependencies are landed. Dispatch it with the mission "read your
      ticket at <the slice's committed ticket path>" - ticket files are
      COMMITTED (worktrees cannot see untracked files); relay every
      path the ticket names. After accept_dispatch, run the plan's
      GATE COMMAND as your verification. Gate green -> edit state.json
      (slice -> "landed", the sha, gate green) and commit code +
      state.json TOGETHER, with this trailer as the LAST line of the
      commit message:
        Slice: <feature-id>.<slice-n>
      One slice per commit. Never commit while a review is pending.
      Gate red -> re-dispatch ONCE with the exact error output; a slice
      that fails its gate twice is marked "failed" in state.json - move
      to the next independent slice, do not grind.

      STAGGER (hard rule): never launch two COLD members in the same
      turn - the local server prefills one context at a time and a
      mass launch stalls every agent on the box. Dispatch the second
      member only after the first shows progress (check_task), or
      after `sleep 35` in your terminal. At most TWO members in flight,
      and only when plan.md marks their slices independent.

      HEARTBEAT: after every landed slice, append ONE line to the
      board's heartbeat.log via terminal (untracked - never commit it):
        echo "$(date -u +%H:%M) landed <slice> <short-sha> gate=green" >> <board>/heartbeat.log

      PARK (objective triggers ONLY: acceptance criteria underivable,
      spec contradicts the repo, attempts exhausted): append the
      question + evidence + what you tried to parked.md, set the slice
      to "parked" in state.json, commit both, move on. Never invent
      requirements to unblock yourself.

      EXIT - the only three endings. When the harness reports your
      context is at the handoff threshold, or no dispatchable slice
      remains: finish or reject the dispatch in flight, commit
      anything landed and verified, REWRITE handoff-current.md (three
      short sections: WHERE I STOPPED / NEXT SLICE TO TAKE /
      ANOMALIES), commit it, then declare_done with the FIRST WORD of
      the summary being exactly one of:
        DONE    - every slice in plan.md is landed and gate-verified
        HANDOFF - work remains; the board tells the next generation
        BLOCKED - every remaining slice is parked or failed; Mark must
                  act before any generation can continue
      The CONFIDENCE/REASON lines still end the summary. Never start
      new work after the wrap-up instruction arrives.
    # 200, not 25:"""
local = patch(local, OLD_LEADER_END, RELAY_RULES, "leader prompt end")

# ---------------- 4. leader compaction block ------------------------------
OLD_LEADER_ITER = """    max_iterations: 200
    llm:
      temperature: 0.3
      top_p: 0.95"""
NEW_LEADER_ITER = """    max_iterations: 200
    # Leader budget 50K (capacity study). Explicit here so a future edit
    # to the root block cannot silently change the leader's budget.
    compaction:
      threshold_tokens: 50000
      keep_last_messages: 8
    llm:
      temperature: 0.3
      top_p: 0.95"""
local = patch(local, OLD_LEADER_ITER, NEW_LEADER_ITER, "leader max_iterations/llm")

# ---------------- 5. member budgets ---------------------------------------
def member_budget(t, iters, tokens, who):
    old = "      max_iterations: %d\n" % iters
    new = ("      # %s budget %dK (capacity study: builders/verifier 20-30K).\n"
           "      compaction:\n"
           "        threshold_tokens: %d\n"
           "        keep_last_messages: 5\n"
           "      max_iterations: %d\n" % (who, tokens // 1000, tokens, iters))
    return patch(t, old, new, "%s max_iterations" % who)

local = member_budget(local, 40, 30000, "implementer")
local = member_budget(local, 25, 20000, "researcher")
local = member_budget(local, 20, 20000, "reviewer")

io.open(DST_LOCAL, "w", encoding="utf-8", newline="").write(local)
print("wrote ds-relay-local.yaml (%d bytes)" % len(local))

# ---------------- 6. hybrid = local with Pro reviewer + new header --------
hybrid = HEADER_HYBRID + local[local.index("sandbox:"):]
OLD_REVIEWER_LLM = """      max_iterations: 20
      llm:
        temperature: 0.3
        top_p: 0.95"""
NEW_REVIEWER_LLM = """      max_iterations: 20
      llm:
        # reviewer: judgment role -> DeepSeek-V4-PRO via OpenRouter (the
        # proven ds-team-lead-pro pattern). Everything else stays local
        # Flash. enable_thinking deliberately unset (2.5x tokens).
        provider: local
        endpoint: https://openrouter.ai/api/v1
        model: deepseek/deepseek-v4-pro
        api_key_env: DEEPSEEK_API_KEY
        temperature: 0.3
        top_p: 0.95
        request_timeout_seconds: 900
        num_retries: 2"""
hybrid = patch(hybrid, OLD_REVIEWER_LLM, NEW_REVIEWER_LLM, "reviewer llm block")

io.open(DST_HYBRID, "w", encoding="utf-8", newline="").write(hybrid)
print("wrote ds-relay-hybrid.yaml (%d bytes)" % len(hybrid))

# ---------------- 7. ds-team-flash-escalate (M6/T7) --------------------------
# Base = ds-team-flash VERBATIM (not the relay variant): the ladder is a
# team-mode feature; measured runs keep using the pristine local profile.
DST_ESC = os.path.join(HERE, "ds-team-flash-escalate.yaml")
HEADER_ESC = """name: ds-team-flash-escalate
description: |
  ESCALATION LADDER (M6/T7, 2026-07-10): ds-team-flash plus ONE extra
  member, implementer-pro (DeepSeek-V4-PRO via OpenRouter), and a leader
  escalation rule: Flash implements FIRST; a subtask escalates to Pro
  ONLY after the verify gate fails twice on it. Monotonic - never bumps
  back down on the same subtask; never triggered by a member's
  self-report (DeepSeek confidence is anti-correlated with truth).

  This is the CONVENTION-level ladder (leader prompt + second tier in
  YAML). The harness-owned verifier-fail counter that FORCES the bump
  on a stubborn leader is future work (T7 mechanics); until it exists,
  treat ladder compliance as unproven and audit run.jsonl.

  FLAG-OFF RULE (Mark): a team that can escalate can never tell you what
  Flash alone can do. Anything MEASURED (ladders, benchmarks, the first
  24h run) uses ds-team-flash, never this profile. Farm volume:
  forbidden (escalation swaps model identity mid-instance -> destroys
  attribution).

  Requires: DEEPSEEK_API_KEY = OpenRouter token (implementer-pro only).
  Member prompt set byte-identical to the proven baseline (generated by
  gen_relay_profiles.py; fix the baseline and regenerate).

"""
esc = HEADER_ESC + text[text.index("sandbox:"):]

OLD_MEMBERS_LINE = """      Available members: implementer, researcher, reviewer
        - researcher: read-only investigation — reading/inspecting files,
          answering questions about the workspace. Use for any task that
          only READS and REPORTS, never edits.
        - implementer: makes changes — creating/editing files, running tests.
        - reviewer: assesses a change for correctness without rewriting it.
      Pick the member whose ROLE matches the task. A "have the researcher
      read X and tell me" task MUST go to researcher, not implementer."""
NEW_MEMBERS_LINE = """      Available members: implementer, implementer-pro, researcher, reviewer
        - researcher: read-only investigation — reading/inspecting files,
          answering questions about the workspace. Use for any task that
          only READS and REPORTS, never edits.
        - implementer: makes changes — creating/editing files, running tests.
        - implementer-pro: STRONGER, PAID implementation tier. See the
          ESCALATION LADDER rule below for when it may be used.
        - reviewer: assesses a change for correctness without rewriting it.
      Pick the member whose ROLE matches the task. A "have the researcher
      read X and tell me" task MUST go to researcher, not implementer.

      ESCALATION LADDER (hard rule): every implementation subtask goes to
      `implementer` (the cheap tier) FIRST. You may dispatch
      `implementer-pro` for a subtask ONLY after the build/verify gate
      has failed on that SAME subtask in TWO separate implementer
      dispatches. Never escalate on a member's self-report or your own
      hunch - only on two failed gate results. Once a subtask escalates
      it NEVER goes back to `implementer`. Escalations are expensive:
      dispatch implementer-pro with the exact accumulated error output."""
esc = patch(esc, OLD_MEMBERS_LINE, NEW_MEMBERS_LINE, "leader members list")

# Add implementer-pro: copy the implementer block (prompt byte-identical),
# rename, and give it the Pro cloud llm.
mstart = esc.index("    - name: implementer\n")
mend = esc.index("    - name: researcher\n")
impl_block = esc[mstart:mend]
pro_block = impl_block.replace("    - name: implementer\n",
                               "    - name: implementer-pro\n", 1)
OLD_IMPL_LLM = """      llm:
        # Inherits LOCAL V4-Flash from the profile root.
        temperature: 0.3
        top_p: 0.95
"""
NEW_PRO_LLM = """      llm:
        # ESCALATION TIER: DeepSeek-V4-PRO via OpenRouter (paid).
        # enable_thinking deliberately unset (2.5x tokens).
        provider: local
        endpoint: https://openrouter.ai/api/v1
        model: deepseek/deepseek-v4-pro
        api_key_env: DEEPSEEK_API_KEY
        temperature: 0.3
        top_p: 0.95
        request_timeout_seconds: 900
        num_retries: 2
"""
if OLD_IMPL_LLM not in pro_block:
    print("ANCHOR MISSING: implementer llm block for pro copy"); sys.exit(1)
pro_block = pro_block.replace(OLD_IMPL_LLM, NEW_PRO_LLM, 1)
esc = esc[:mend] + pro_block + esc[mend:]

io.open(DST_ESC, "w", encoding="utf-8", newline="").write(esc)
print("wrote ds-team-flash-escalate.yaml (%d bytes)" % len(esc))
